[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "ranged_ray_torch_backend"
version = "0.0.0"
dependencies = [
    "ray[train]"
]
requires-python = ">=3.11"
authors = [
    { name = "plumiume", email = "plumiiume@gmail.com" }
]